### ISSUE TITLE
Требуются правки.

### ISSUE THREAD

**Issue by s3rius** [endlessmeal/simbirsoft_django#1]
Отдельная фильтрация по ценам, датам и тегам это неудобно. То есть, если мои условия поиска будут совмещать несколько условий, то мне надо будет сделать несколько запросов и потом ещё сделать какие-то действия, чтобы сложить резльтаты воедино. Это не самая удобная штука. Куда лучше один эндпоинт поиска.

Также у тебя [flake8](https://pypi.org/project/flake8/) ругается на код, надо пофиксить.
Также пробегись всякими штуками для фиксов стилей. [black](https://pypi.org/project/black/) и [isort](https://pypi.org/project/isort/).

**Comment by endlessmeal** [comment]
Исправил.
